#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/polybar/turja/scripts"
RASI="$DIR/rofi/networkmenu.rasi"

# Run
rofi \
    -show drun \
	-theme ${RASI}
