$font = Iosevka Nerd Font

general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = false
    ignore_empty_input = false
}

animations {
    enabled = true

    bezier = instant, 0, 0, 0, 0

    animation = fadeIn, 1, 0.2, smooth
    animation = fadeOut, 0, 0, instant
    animation = inputFieldDots, 0, 0, instant
}

# # Background Option 1: Screenshot with blur
# background {
#     monitor =
#     path = screenshot
#     blur_passes = 3
#     blur_size = 5
# }

# Background Option 2: Wallpaper from Variety
background {
    monitor =
    path = /home/turja/.config/variety/Favorites/IMG_20251118_013625_727.jpg
    blur_passes = 3
    blur_size = 5
}

input-field {
    monitor =
    size = 300, 300
    outline_thickness = 20

    hide_input = true

    outer_color = rgba(ffffffff)
    inner_color = rgba(00000000)
    capslock_color = rgba(ff0066aa)
    numlock_color = rgba(00000000)
    bothlock_color = rgba(ff0066aa)
    font_color = rgba(ffffffff)

    check_color = rgba(ffffffff)
    fail_color = rgba(ff0066ee)

    fade_on_empty = false
    rounding = -1

    font_family = $font
    font_size = 14
    placeholder_text = 
    capslock_text =
    fail_text =
    fail_timeout = 2000

    position = 0, 0
    halign = center
    valign = center
}

# AUTHENTICATION FAIL
label {
    monitor =
    text = $FAIL <span style="italic">($ATTEMPTS)</span>
    color = rgba(ff0066ff)
    font_size = 16
    font_family = $font
    
    position = 0, -250
    halign = center
    valign = center
}

# CAPS LOCK WARNING
label {
    monitor =
    text = cmd[update:200] [ "$(cat /sys/class/leds/input4::capslock/brightness)" = "1" ] && echo "⚠ CAPS LOCK" || echo ""
    color = rgba(ff0066ff)
    font_size = 20
    font_family = $font
    
    position = 0, -200
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p"
    color = rgba(ffffffff)
    font_size = 50
    font_family = $font
    
    position = 0, 30
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%a, %e %B"
    color = rgba(ffffffff)
    font_size = 16
    font_family = $font
    
    position = 0, -20
    halign = center
    valign = center
}
