####################
### WINDOWSRULES ###
####################

windowrule {
    name = windowrule-1
    float = on
    center = on
    size = (monitor_w*0.65) (monitor_h*0.7)
    match:title = (Alacritty)$
}

windowrule {
    name = windowrule-2
    tile = on
    match:title = (yazi)$
}


windowrule {
    name = windowrule-3
    float = on
    match:title = (CopyQ)
}


windowrule {
    name = windowrule-4
    float = on
    size = (monitor_w*0.3) (monitor_h*0.6)
    match:title = (Volume Control)
}


windowrule {
    name = windowrule-5
    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.7)
    match:title = (Notejot)
}


windowrule {
    name = windowrule-6
    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.7)
    match:title = (Folio)
}


# windowrule = float, title:(Proton VPN)
# windowrule = center, title:(Proton VPN)
# windowrule = size 50% 30%, title:(Proton VPN)

windowrule {
    name = windowrule-7
    float = on
    center = on
    size = (monitor_w*0.3) (monitor_h*0.5)
    match:title = (Pulse Secure)
}


windowrule {
    name = windowrule-8
    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
    match:title = (Waypaper)
}


windowrule {
    name = windowrule-8
    float = on
    center = on
    size = (monitor_w*0.125) (monitor_h*0.3)
    match:title = (Pomodorolm)
}
