[font]
size = 11

builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Source Code Pro"

[font.bold]
family = "JetBrainsMono Nerd Font"
# family = "Source Code Pro"

[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "Source Code Pro"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
# family = "Source Code Pro"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
